### ISSUE TITLE
Building with gcc-7 compiler fails

### ISSUE THREAD

**Issue by jeremyroy** [smartmicro/smartmicro_ros2_radars#17]
When building with the gcc-7 compiler I get the following error message:

```
Starting >>> umrr_ros2_driver
--- stderr: umrr_ros2_driver                             
In file included from /root/autoTram/src/at_submodules/smartmicro_ros2_radars/umrr_ros2_driver/src/smartmicro_radar_node.cpp:39:0:
/root/autoTram/build/umrr_ros2_driver/_deps/json-src/single_include/nlohmann/json.hpp:3954:14: fatal error: filesystem: No such file or directory
     #include <filesystem>
              ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/smartmicro_radar_node.dir/src/smartmicro_radar_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/smartmicro_radar_node.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< umrr_ros2_driver [3.63s, exited with code 2]

Summary: 2 packages finished [5.70s]
  1 package failed: umrr_ros2_driver
```

It looks like the error is related to this issue: https://github.com/nlohmann/json/issues/3090
Further, it looks like the issue was resolved in v3.10.5 of the library: https://github.com/nlohmann/json/releases/tag/v3.10.5

Updating the version tag of the json repository to v3.10.5 in `CMakeLists.txt` resolves the issue:

```
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG v3.10.5
)
```

**Comment by smartSRA** [comment]
Hey @jeremyroy,

Thanks fro pointing this out. Good to know, it has been addressed. Nonetheless, in the upcoming release #13 I have already increased the `nlohmannjson` tag to `v3.10.5`. 

I am closing this issue as this has been resolved.
