### ISSUE TITLE
Wrong print message

### ISSUE THREAD

**Issue by chilisam** [smartmicro/smartmicro_ros2_radars#23]
in 
https://github.com/smartmicro/smartmicro_ros2_radars/blob/a08720ba2294bb3271b9f24489e8adc4d14528ef/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L167
and
https://github.com/smartmicro/smartmicro_ros2_radars/blob/a08720ba2294bb3271b9f24489e8adc4d14528ef/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L167

the message should be "... for sensor umrr96" and "... for sensor umrr9f" respectively.

**Comment by smartSRA** [comment]
> in
> 
> https://github.com/smartmicro/smartmicro_ros2_radars/blob/a08720ba2294bb3271b9f24489e8adc4d14528ef/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L167
> 
> 
> and
> https://github.com/smartmicro/smartmicro_ros2_radars/blob/a08720ba2294bb3271b9f24489e8adc4d14528ef/umrr_ros2_driver/src/smartmicro_radar_node.cpp#L167
> 
> the message should be "... for sensor umrr96" and "... for sensor umrr9f" respectively.

Yup, I came across this. Would be updated in the patch.
