### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by umsarmy** [smartmicro/smartmicro_ros2_radars#29]
[smartmicro_radar_node_exe-1] terminate called after throwing an instance of 'nlohmann::detail::parse_error'
[smartmicro_radar_node_exe-1]   what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

**Comment by smartSRA** [comment]
Hey,

It seems you are mixing up docker and standard commands which is leading to problem in your file paths. As I am not entirely sure which steps you took to build the driver, delete your “build” and “install” folder and follow the following steps:

1) source your terminal
2) `colcon build` from root of your workspace
3) source your workspace
2) `ros2 launch umrr_ros2_driver radar.launch.py` also called from root of your workspace.

**Comment by umsarmy** [comment]
Hi @smartSRA, Thanks for a quick reply.

I followed the streps and the issue got resolved. Thanks!

**Comment by umsarmy** [comment]
However, I am not able to see any data on the rostopic

/smart_radar/targets_0
/smart_radar/targets_1
/smart_radar/targets_2
/smart_radar/targets_3

I have uploaded a screenshot of my radar.template.yaml.
I am using UMRR11 Type 132.


![Screenshot from 2023-02-17 12-20-53](https://user-images.githubusercontent.com/22838868/219570789-55599910-273f-41ec-9445-92083d8f28d8.png)

**Comment by smartSRA** [comment]
Hey,

The params look fine. Could you verify if you are using a compatible sensor firmware with the driver? The compatible versions are mentioned in the Readme.

**Comment by umsarmy** [comment]
Thanks, @smartSRA for the reply.

Actually, I got it worked by just changing the ipv4 address of my laptop from _**192.168.11.99**_ to _**192.168.11.17**_.

Other things remained the same.

**Comment by umsarmy** [comment]
@smartSRA Do you why it only works when my system IP is 192.168.11.17? Why I can't use other IP addresses?

**Comment by smartSRA** [comment]
> Thanks, @smartSRA for the reply.
> 
> Actually, I got it worked by just changing the ipv4 address of my laptop from _**192.168.11.99**_ to _**192.168.11.17**_.
> 
> Other things remained the same.

Yes, it should have been `192.168.11.17`.

**Comment by smartSRA** [comment]
> @smartSRA Do you why it only works when my system IP is 192.168.11.17? Why I can't use other IP addresses?

This is the default ip address for the source in the sensor configuration. The sensor looks for this source when trying to communicate. In order to use another ip address it could be modified. This could be achieved using the driverecorder tool and how to achieve this should be mentioned in the sensor configuration manual.

**Comment by umsarmy** [comment]
OK. Thanks
