### ISSUE TITLE
change mode of operation 

### ISSUE THREAD

**Issue by smartSRA** [smartmicro/smartmicro_ros2_radars#3]
Provide ros2 services to be able to change the mode of operation of the sensor and also to be able to configure the IP_address of the sensor.

**Comment by nrKDot** [comment]
Hi team. Is there a timeline for when these ros2 service features might be complete?

**Comment by smartSRA** [comment]
We encountered some bugs which hindered from pursuing the PR #1. This was put to a halt. We need to move to the update of the driver with the new release which fixes the bugs and that is already on its ways. After the update we should focus back on the pending PR #1.
