### ISSUE TITLE
Topic name in radar.rviz

### ISSUE THREAD

**Issue by adithyab94** [smartmicro/smartmicro_ros2_radars#42]
Hi,

I noticed a small mistake. the topic name should be `/smart_radar/targets_0` here

https://github.com/smartmicro/smartmicro_ros2_radars/blob/587467f78bc2e64422d4989fc89c025409af8f01/umrr_ros2_driver/config/rviz/radar.rviz#L77C17-L77C21

**Comment by smartSRA** [comment]
Hey,

Thank you for pointing out. I have noted it and would make a fix in the upcoming PR.
