### ISSUE TITLE
Missing/wrong dependencies for smart_rviz_plugin 

### ISSUE THREAD

**Issue by Hawxxer** [smartmicro/smartmicro_ros2_radars#51]
Hi,
I had several dependency and package issues preventing the successful build of the smart_rviz_plugin node. The following problems were identified:

1. Missing Dependencies:
        ros-foxy-cv-bridge
        libopencv-dev

    Suggestion: Consider adding the cv_bridge package to package.xml. It's unclear if the OpenCV library can be added similarly.
    
2. Incorrect Package Dependency:
    Current: <exec_depend>rviz</exec_depend>
    This throws an error with rosdep. 

    Suggested correction: <exec_depend>rviz2</exec_depend> This appears to be the correct package for ROS 2 Foxy.
    
3. Python Package Requirement:
    The custom_can_sender.py script requires the tkinter package, which is not included in the default Python installation on some systems (e.g., Foxy Docker image). 

    Solution: Install the python3-tk package via apt.

Steps to Reproduce:

    Attempt to build the smart_rviz_plugin node
    Observe build failures due to missing dependencies
    Try running custom_can_sender.py and note the missing tkinter package

Environment:

    ROS 2 Foxy
    Docker environment

**Comment by smartSRA** [comment]
Hey,

Sorry for the delayed reply. The issue you are encountering is on purpose. I left out the smart_rviz_plugins as running rviz in docker is not ideal and especially for the building and testing for which I am using the docker image here was causing issues.

https://github.com/smartmicro/smartmicro_ros2_radars/blob/ad4e9b211cbfe1d64565ed07559cd841aaadc398/.github/workflows/dockerbuild.yml#L24

On the other side, if you go for native builds all the dependencies are covered and you could probably get the missing dependencies from there.
